[sim]
seed = 424242
duration_ms = 30000

[topology]
type = "small_world"
n = 24
k = 6
rewire_p = 0.2

[traffic.tx]
publisher_bias = { type = "zipf", s = 0.9 }

[[traffic.tx.phases]]
name = "warmup"
duration_ms = 5000
model = "poisson"
lambda_per_sec = 10.0

[[traffic.tx.phases]]
name = "bursty"
duration_ms = 15000
model = "on_off_bursty"
on_lambda_per_sec = 18.0
on_duration_ms = 1500
off_duration_ms = 600

[[traffic.tx.phases]]
name = "cooldown"
duration_ms = 10000
model = "poisson"
lambda_per_sec = 6.0

[metrics]
json = "target/sim-smoke/high-density-summary.json"
csv = "target/sim-smoke/high-density-summary.csv"
