[sim]
seed = 1337
duration_ms = 86400000

[topology]
type = "small_world"
n = 40
k = 8
rewire_p = 0.25

[regions]
assignments = [
  "alpha", "alpha", "alpha", "alpha", "alpha", "alpha", "alpha", "alpha", "alpha", "alpha",
  "beta", "beta", "beta", "beta", "beta", "beta", "beta", "beta", "beta", "beta",
  "gamma", "gamma", "gamma", "gamma", "gamma", "gamma", "gamma", "gamma", "gamma", "gamma",
  "delta", "delta", "delta", "delta", "delta", "delta", "delta", "delta", "delta", "delta"
]

[links]
default = { delay_ms = 45, jitter_ms = 12, loss = 0.005 }
alpha-beta = { delay_ms = 85, jitter_ms = 24, loss = 0.015 }
beta-gamma = { delay_ms = 70, jitter_ms = 20, loss = 0.01 }
gamma-delta = { delay_ms = 95, jitter_ms = 30, loss = 0.02 }
alpha-delta = { delay_ms = 110, jitter_ms = 35, loss = 0.025 }

[traffic.tx]
publisher_bias = { type = "zipf", s = 1.15 }

[[traffic.tx.phases]]
name = "baseline"
duration_ms = 10800000
model = "poisson"
lambda_per_sec = 14.0

[[traffic.tx.phases]]
name = "reorg-storm"
duration_ms = 21600000
model = "on_off_bursty"
on_lambda_per_sec = 42.0
on_duration_ms = 600000
off_duration_ms = 120000

[[traffic.tx.phases]]
name = "recovery"
duration_ms = 54000000
model = "poisson"
lambda_per_sec = 10.0

[metrics]
json = "target/simnet/multinode-soak/summary.json"

[faults.partition]
start_ms = 10800000
duration_ms = 3600000
group_a = "alpha"
group_b = "beta"

[faults.churn]
start_ms = 3600000
rate_per_min = 45.0
restart_after_ms = 120000

[faults.byzantine]
start_ms = 21600000
spam_factor = 5
publishers = [3, 17, 29]
