[sim]
seed = 42
duration_ms = 10000

[topology]
type = "ring"
n = 8
k = 2

[regions]
assignments = ["EU", "US", "EU", "US", "EU", "US", "EU", "US"]

[links]
intra = { delay_ms = 10, jitter_ms = 1, loss = 0.0 }
EU-US = { delay_ms = 75, jitter_ms = 12, loss = 0.5 }

[traffic.tx]
model = "poisson"
lambda_per_sec = 5.0

[faults.partition]
start_ms = 2000
duration_ms = 3000
group_a = "EU"
group_b = "US"

[faults.churn]
start_ms = 1000
rate_per_min = 120.0
restart_after_ms = 500

[faults.byzantine]
start_ms = 1500
spam_factor = 3
publishers = [0]
