[package]
name = "rpp-p2p-macros"
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[lib]
proc-macro = true

[dependencies]
heck = "0.5"
quote = "1.0"
syn = { version = "2.0.66", default-features = false, features = ["clone-impls", "derive", "parsing", "printing", "proc-macro"] }
