[package]
name = "stwo"
version = "1.0.0"
edition = "2021"
description = "Local STWO proof system fork for the RPP project"
authors = ["RPP Labs <dev@rpp.example>"]
license = "MIT"

[dependencies]
blake2 = "0.10"
rand = { version = "0.8", features = ["std_rng"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
hex = "0.4"

[dev-dependencies]
serde_json = "1.0"
