metrics:
  - name: consensus_quorum_verifications_total
    labels:
      - reason
      - result
  - name: consensus_vrf_verification_time_ms
    labels:
      - reason
      - result
  - name: consensus_vrf_verifications_total
    labels:
      - reason
      - result
  - name: rpp.runtime.chain.block_height
    labels: []
  - name: rpp.runtime.consensus.block_duration
    labels:
      - stage
  - name: rpp.runtime.consensus.failed_votes
    labels:
      - reason
  - name: rpp.runtime.consensus.round.duration
    labels:
      - height
      - round
  - name: rpp.runtime.consensus.round.leader_changes
    labels:
      - height
      - leader
      - round
  - name: rpp.runtime.consensus.round.quorum_latency
    labels:
      - height
      - round
  - name: rpp.runtime.consensus.slashing.events
    labels:
      - reason
  - name: rpp.runtime.consensus.witness.events
    labels:
      - topic
  - name: rpp.runtime.network.peer_count
    labels: []
  - name: rpp.runtime.proof.generation.count
    labels:
      - backend
  - name: rpp.runtime.proof.generation.duration
    labels:
      - backend
  - name: rpp.runtime.proof.generation.size
    labels:
      - backend
  - name: rpp.runtime.proof.cache.hits
    labels:
      - cache
      - backend
  - name: rpp.runtime.proof.cache.misses
    labels:
      - cache
      - backend
  - name: rpp.runtime.proof.cache.evictions
    labels:
      - cache
      - backend
  - name: rpp.runtime.reputation.penalties
    labels:
      - label
  - name: rpp.runtime.rpc.request.latency
    labels:
      - method
      - result
  - name: rpp.runtime.rpc.request.total
    labels:
      - method
      - result
  - name: rpp.runtime.rpc.rate_limit.total
    labels:
      - method
      - status
  - name: rpp.runtime.storage.header_flush.bytes
    labels: []
  - name: rpp.runtime.storage.header_flush.duration
    labels: []
  - name: rpp.runtime.storage.header_flush.total
    labels: []
  - name: rpp.runtime.storage.wal_flush.bytes
    labels:
      - outcome
  - name: rpp.runtime.storage.wal_flush.duration
    labels:
      - outcome
  - name: rpp.runtime.storage.wal_flush.total
    labels:
      - outcome
  - name: rpp.runtime.storage.cache.hits
    labels:
      - cache
  - name: rpp.runtime.storage.cache.misses
    labels:
      - cache
  - name: rpp.runtime.storage.cache.evictions
    labels:
      - cache
  - name: firewood.nodestore.unwritten_nodes
    labels: []
  - name: firewood.allocations.from_end
    labels:
      - index
  - name: firewood.allocations.reused
    labels:
      - index
  - name: firewood.allocations.reused.split
    labels:
      - area_size
  - name: firewood.allocations.reused.whole
    labels:
      - area_size
  - name: firewood.cache.freelist
    labels:
      - type
  - name: firewood.cache.node
    labels:
      - mode
      - type
  - name: firewood.checker.leaked_areas.detected
    labels: []
  - name: firewood.checker.leaked_areas.failed_to_fix
    labels: []
  - name: firewood.checker.leaked_areas.fixed
    labels: []
  - name: firewood.checker.leaked_ranges
    labels: []
  - name: firewood.checker.leaked_ranges.detected
    labels: []
  - name: firewood.commit.wal_flush.queue_depth
    labels: []
  - name: firewood.commit.wal_flush.wait_seconds
    labels: []
  - name: firewood.freelist.available
    labels:
      - index
  - name: firewood.freelist.corrupt_header
    labels:
      - index
  - name: firewood.freelist.split
    labels:
      - from_index
      - target_index
  - name: firewood.io.read
    labels: []
  - name: firewood.io.read_ms
    labels: []
  - name: firewood.nodestore.ethhash.corrupt_proof
    labels:
      - reason
  - name: firewood.nodestore.root.read_errors
    labels:
      - state
  - name: firewood.nodestore.serialize.avg_capacity_hint
    labels: []
  - name: firewood.nodestore.serialize.avg_len
    labels: []
  - name: firewood.nodestore.serialize.max_capacity_hint
    labels: []
  - name: firewood.nodestore.serialize.max_len
    labels: []
  - name: firewood.nodestore.serialize.nodes
    labels: []
  - name: firewood.nodestore.serialize.reserve_miss
    labels: []
  - name: firewood.nodestore.serialize.reserve_miss_bytes
    labels: []
  - name: firewood.nodestore.serialize.reserve_miss_count
    labels: []
  - name: firewood.read_node
    labels:
      - from
  - name: firewood.recovery.active
    labels: []
  - name: firewood.recovery.runs
    labels:
      - phase
  - name: firewood.space.from_end
    labels:
      - index
  - name: firewood.space.freed
    labels:
      - index
  - name: firewood.space.reused
    labels:
      - index
  - name: firewood.space.wasted
    labels:
      - index
  - name: firewood.snapshot.ingest.failures
    labels:
      - reason
  - name: firewood.storage.bytes_written
    labels:
      - cf
  - name: firewood.storage.io_budget
    labels:
      - stage
  - name: firewood.storage.io_uring_ring_entries
    labels: []
  - name: firewood.wal.transactions
    labels:
      - result
  - name: rpp.runtime.wallet.rpc_latency
    labels:
      - method
  - name: rpp.runtime.wallet.action.total
    labels:
      - action
      - outcome
  - name: rpp.runtime.wallet.prover.witness.bytes
    labels:
      - backend
  - name: rpp.runtime.wallet.prover.jobs
    labels:
      - backend
      - result
  - name: rpp.runtime.wallet.prover.failures
    labels:
      - backend
      - code
  - name: rpp.runtime.wallet.sign.latency_ms
    labels:
      - mode
      - account_type
      - backend
      - result
  - name: rpp.runtime.wallet.sign.failures
    labels:
      - mode
      - account_type
      - backend
      - code
  - name: rpp.runtime.wallet.sync.wallet_height
    labels: []
  - name: rpp.runtime.wallet.sync.chain_tip_height
    labels: []
  - name: rpp.runtime.wallet.sync.lag.blocks
    labels: []
  - name: rpp.runtime.wallet.sync.last_success_timestamp.seconds
    labels: []
  - name: rpp_stark_params_bytes
    labels:
      - proof_backend
      - proof_kind
    alternate_labels:
      - - proof_backend
        - proof_kind
        - stage
  - name: rpp_stark_payload_bytes
    labels:
      - proof_backend
      - proof_kind
    alternate_labels:
      - - proof_backend
        - proof_kind
        - stage
  - name: rpp_stark_proof_total_bytes
    labels:
      - proof_backend
      - proof_kind
    alternate_labels:
      - - proof_backend
        - proof_kind
        - stage
  - name: rpp_stark_public_inputs_bytes
    labels:
      - proof_backend
      - proof_kind
    alternate_labels:
      - - proof_backend
        - proof_kind
        - stage
  - name: rpp_stark_stage_checks_total
    labels:
      - proof_backend
      - proof_kind
      - result
      - stage
  - name: rpp_stark_verify_duration_seconds
    labels:
      - proof_backend
      - proof_kind
    alternate_labels:
      - - proof_backend
        - proof_kind
        - stage
  - name: rpp.node.pruning.cycle_duration_ms
    labels:
      - shard
      - partition
      - reason
      - result
  - name: rpp.node.pruning.cycle_total
    labels:
      - shard
      - partition
      - reason
      - result
  - name: rpp.node.pruning.failures_total
    labels:
      - shard
      - partition
      - reason
      - error
  - name: rpp.node.pruning.keys_processed
    labels:
      - shard
      - partition
      - reason
  - name: rpp.node.pruning.missing_heights
    labels:
      - shard
      - partition
  - name: rpp.node.pruning.pause_transitions
    labels:
      - shard
      - partition
      - state
  - name: rpp.node.pruning.persisted_plan_total
    labels:
      - shard
      - partition
      - reason
      - persisted
  - name: rpp.node.pruning.retention_depth
    labels:
      - shard
      - partition
  - name: rpp.node.pruning.stored_proofs
    labels:
      - shard
      - partition
  - name: rpp.node.pruning.time_remaining_ms
    labels:
      - shard
      - partition
      - reason
  - name: telemetry_otlp_failures_total
    labels:
      - phase
      - sink
