# Default RPP Chain configuration

config_version = "1.0"

data_dir = "./data"
key_path = "./keys/node.toml"
p2p_key_path = "./keys/p2p.toml"
vrf_key_path = "./keys/vrf.toml"

[secrets]
backend = "filesystem"

snapshot_dir = "./data/snapshots"
proof_cache_dir = "./data/proofs"
rpc_listen = "127.0.0.1:7070"
rpc_requests_per_minute = 600
block_time_ms = 5000
max_block_transactions = 512
max_block_identity_registrations = 32
mempool_limit = 8192
epoch_length = 1440
target_validator_count = 100
max_proof_size_bytes = 4194304

[queue_weights]
priority = 0.7
fee = 0.3

[p2p]
listen_addr = "/ip4/0.0.0.0/tcp/7600"
bootstrap_peers = []
heartbeat_interval_ms = 5000
gossip_enabled = true
gossip_rate_limit_per_sec = 128
replay_window_size = 1024
peerstore_path = "./data/p2p/peerstore.json"
gossip_path = "./data/p2p/gossip.json"

[rollout]
release_channel = "development"

[rollout.feature_gates]
pruning = true
recursive_proofs = true
reconstruction = true
consensus_enforcement = true
malachite_consensus = false
timetoke_rewards = false
witness_network = false

[rollout.telemetry]
enabled = false
sample_interval_secs = 30

[reputation.tier_thresholds]
tier2_min_uptime_hours = 24
tier3_min_consensus_success = 10
tier4_min_consensus_success = 100
tier5_min_score = 0.75

[reputation.weights]
# All reputation weights must be between 0.0 and 1.0 and sum to 1.0.
validation = 0.4
uptime = 0.2
consensus = 0.2
peer_feedback = 0.15
decay = 0.05

[genesis]
chain_id = "rpp-local"

[[genesis.accounts]]
address = "GENESIS_ADDRESS_PLACEHOLDER"
balance = 1000000000
stake = "1000"
