#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/verify_checksums.sh --manifest <file>

Validate a SHA256 manifest generated by scripts/checksums.sh.
USAGE
}

MANIFEST=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest)
      [[ $# -lt 2 ]] && { echo "error: --manifest requires a value" >&2; exit 1; }
      MANIFEST="$2"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option '$1'" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$MANIFEST" ]]; then
  echo "error: --manifest is required" >&2
  usage >&2
  exit 1
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "error: manifest '$MANIFEST' not found" >&2
  exit 1
fi

if command -v sha256sum >/dev/null 2>&1; then
  sha256sum --check "$MANIFEST"
elif command -v shasum >/dev/null 2>&1; then
  shasum -a 256 -c "$MANIFEST"
else
  echo "error: neither sha256sum nor shasum is available" >&2
  exit 1
fi
