apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: telemetry-exporters
  labels:
    role: alert-rules
spec:
  groups:
    - name: telemetry-exporters
      rules:
        - alert: OtlpExporterFailure
          expr: increase(telemetry_otlp_failures_total[15m]) > 0
          for: 10m
          labels:
            severity: warning
            service: observability
          annotations:
            summary: OTLP telemetry exporters are failing to initialise
            description: |
              At least one OTLP exporter failed to initialise within the last 15 minutes.
              Inspect the node logs for `failed to initialise OTLP` warnings, verify
              TLS material and collector reachability, and restart the node once the
              exporter configuration is healthy. Alert clears once failure counters
              stay flat for 10 minutes; the companion recovery alert confirms the
              exporters stabilised after failover.
            runbook_url: https://github.com/chainbound/chain/blob/main/docs/observability.md#otlp-exporter-failure-drill
        - alert: OtlpExporterFailureCleared
          expr: increase(telemetry_otlp_failures_total[15m]) == 0
            and max_over_time(telemetry_otlp_failures_total[1h]) > 0
          for: 10m
          labels:
            severity: info
            service: observability
          annotations:
            summary: OTLP telemetry exporters recovered after failover
            description: |
              No new OTLP exporter failures have been observed for 10 minutes after a
              recent outage. Secondary endpoints are stable; downgrade the incident and
              prepare to roll back to the primary backend once TLS and connectivity tests
              pass.
            runbook_url: https://github.com/chainbound/chain/blob/main/docs/observability.md#otlp-exporter-failure-drill
        - alert: RpcRateLimitThrottling
          expr: sum by (method)(rate(rpp_runtime_rpc_rate_limit_total{status="throttled"}[5m])) > 0
          for: 5m
          labels:
            severity: warning
            service: rpc
          annotations:
            summary: RPC requests are being throttled
            description: |
              The RPC rate limiter is throttling requests. Inspect the tagged method in the alert
              and correlate with `rpp.runtime.rpc.rate_limit.total{method,status}` to determine if
              a specific endpoint or tenant is exceeding budgets before raising limits.
            runbook_url: https://github.com/chainbound/chain/blob/main/docs/API_SECURITY.md#rate-limiting-and-abuse-protections
        - alert: ProofVerificationCircuitRegression
          expr: |
            (sum by (proof_backend, proof_circuit)(rate(rpp_runtime_proof_verification_outcomes_total{result="fail"}[10m]))
              /
            sum by (proof_backend, proof_circuit)(rate(rpp_runtime_proof_verification_outcomes_total[10m]))) > 0.02
          for: 10m
          labels:
            severity: warning
            service: proofs
          annotations:
            summary: Proof verification failures exceed 2% for {{ $labels.proof_backend }} {{ $labels.proof_circuit }}
            description: |
              Circuit-specific proof verification failures remain above 2% for 10 minutes. Inspect the
              pipeline proof validation dashboard for the affected backend/circuit and correlate with
              stage-level metrics before accepting new proofs.
            runbook_url: https://github.com/chainbound/chain/blob/main/docs/observability.md#proof-validation
