name: Firewood Recovery Drill

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  recovery-drill:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
      - name: Run Firewood recovery drill scenario
        run: scripts/ci/firewood_recovery.sh
      - name: Upload Firewood recovery artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firewood-recovery-artifacts
          path: logs/firewood-recovery
          if-no-files-found: error
