name: MSRV

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main
      - "release/*"

permissions:
  contents: read
  checks: read
  packages: read

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  msrv-minimal:
    name: MSRV minimal feature matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.79.0
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: msrv-1.79.0-minimal

      - name: Install tooling
        run: |
          cargo install --locked cargo-hack
          cargo install --locked cargo-msrv --version 0.17.1

      - name: Verify lockfile stability
        run: |
          cargo update --locked
          git diff --exit-code Cargo.lock

      - name: Verify declared MSRV
        run: cargo msrv verify --toolchain 1.79.0 --path .

      - name: Check minimal feature matrix
        run: |
          cargo hack check --workspace --all-targets --no-dev-deps --locked --no-default-features
          cargo hack check --workspace --all-targets --no-dev-deps --locked --each-feature \
            --exclude-features nightly-prover --exclude-features prover-stwo --exclude-features prover-stwo-simd

  msrv-full:
    name: MSRV full workspace (stable features)
    runs-on: ubuntu-latest
    needs: msrv-minimal
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.79.0
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: msrv-1.79.0-full

      - name: Install cargo-hack
        run: cargo install --locked cargo-hack

      - name: Verify lockfile stability
        run: |
          cargo update --locked
          git diff --exit-code Cargo.lock

      - name: Check default feature matrix
        run: cargo hack check --workspace --all-targets --no-dev-deps --locked

      - name: Check stable feature matrix
        run: |
          cargo hack check --workspace --all-targets --no-dev-deps --locked \
            --features "integration,vendor_electrs" \
            --exclude-features nightly-prover --exclude-features prover-stwo --exclude-features prover-stwo-simd

  nightly-prover:
    name: Nightly prover feature matrix
    runs-on: ubuntu-latest
    needs: msrv-full
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: nightly-prover

      - name: Install cargo-hack
        run: cargo install --locked cargo-hack

      - name: Check prover feature matrix
        run: |
          cargo hack check --workspace --all-targets --no-dev-deps --locked \
            --features "prover-stwo-simd"
