name: sim-nightly

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  nightly-sim:
    runs-on: ubuntu-latest
    env:
      RPP_SIM_STATIC_KEY_SEED: nightly-smoke
      RPP_SIM_REQUIRE_DETERMINISTIC: "0"
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo directories
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run ignored rpp-sim smoke tests
        run: |
          cargo test -p rpp-sim -- --ignored
          cargo run -p rpp-sim -- --scenario scenarios/small_world_smoke.toml --output target/sim-smoke/nightly-summary.json
