name: sim-nightly

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  nightly-sim:
    runs-on: ubuntu-latest
    env:
      RPP_SIM_STATIC_KEY_SEED: nightly-smoke
      RPP_SIM_REQUIRE_DETERMINISTIC: "0"
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -D warnings
      CARGO_HOME: ${{ github.workspace }}/.cargo
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Audit deterministic cargo environment
        run: |
          expected="$GITHUB_WORKSPACE/.cargo"
          if [ "${CARGO_HOME}" != "$expected" ]; then
            echo "CARGO_HOME mismatch: ${CARGO_HOME} != $expected" >&2
            exit 1
          fi
          if [ "${RUSTFLAGS:-}" != "-D warnings" ]; then
            echo "RUSTFLAGS mismatch: ${RUSTFLAGS:-<unset>}" >&2
            exit 1
          fi
          mkdir -p "$CARGO_HOME"
      - name: Cache cargo directories
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/registry
            ${{ env.CARGO_HOME }}/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run ignored rpp-sim smoke tests
        run: |
          cargo test -p rpp-sim -- --ignored
          cargo run -p rpp-sim -- --scenario scenarios/small_world_smoke.toml --output target/sim-smoke/nightly-summary.json
