name: Stable CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        features: ["", "backend-rpp-stark"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Build workspace (stable${{ matrix.features != '' && format(' + {0}', matrix.features) || '' }})
        env:
          FEATURES: ${{ matrix.features }}
        run: |
          if [ -n "$FEATURES" ]; then
            cargo +1.79.0 build --workspace --features "$FEATURES"
          else
            cargo +1.79.0 build --workspace
          fi

  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        features: ["", "backend-rpp-stark"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Test workspace (stable${{ matrix.features != '' && format(' + {0}', matrix.features) || '' }})
        env:
          FEATURES: ${{ matrix.features }}
        run: |
          if [ -n "$FEATURES" ]; then
            cargo +1.79.0 test --workspace --features "$FEATURES"
          else
            cargo +1.79.0 test --workspace
          fi

  clippy:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        features: ["", "backend-rpp-stark"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Clippy (stable${{ matrix.features != '' && format(' + {0}', matrix.features) || '' }})
        env:
          FEATURES: ${{ matrix.features }}
        run: |
          if [ -n "$FEATURES" ]; then
            cargo +1.79.0 clippy --workspace --features "$FEATURES" -D warnings
          else
            cargo +1.79.0 clippy --workspace -D warnings
          fi

  fmt:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        features: ["", "backend-rpp-stark"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Format check (stable${{ matrix.features != '' && format(' + {0}', matrix.features) || '' }})
        run: cargo +1.79.0 fmt --all -- --check
