name: Stable CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Build workspace (stable)
        run: |
          if cargo +1.79.0 build --workspace --all-features; then
            echo "Stable build succeeded on Rust 1.79.0."
          else
            status=$?
            echo "::warning::Stable build failed on Rust 1.79.0 (exit code $status). Track blockers in docs/STABLE_MIGRATION_REPORT.md."
            exit "$status"
          fi

  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Test workspace (stable)
        run: |
          if cargo +1.79.0 test --workspace --all-features; then
            echo "Stable test suite succeeded on Rust 1.79.0."
          else
            status=$?
            echo "::warning::Stable test suite failed on Rust 1.79.0 (exit code $status). Track blockers in docs/STABLE_MIGRATION_REPORT.md."
            exit "$status"
          fi

  clippy:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Clippy (stable, warnings as errors)
        run: |
          if cargo +1.79.0 clippy --workspace --all-features -D warnings; then
            echo "Stable clippy passed on Rust 1.79.0."
          else
            status=$?
            echo "::warning::Stable clippy failed on Rust 1.79.0 (exit code $status). Track blockers in docs/STABLE_MIGRATION_REPORT.md."
            exit "$status"
          fi

  fmt:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt
      - name: Format check (stable)
        run: |
          if cargo +1.79.0 fmt --all -- --check; then
            echo "Stable fmt check passed on Rust 1.79.0."
          else
            status=$?
            echo "::warning::Stable fmt check failed on Rust 1.79.0 (exit code $status). Track blockers in docs/STABLE_MIGRATION_REPORT.md."
            exit "$status"
          fi
